# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Bostel Technologies
email: 
phone: 
description: >- # this means to ignore newlines until "baseurl:"

  
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
  
twitter_username: 
github_username:  

linkedin_url: 
medium_url: 
twitter_url: 
github_url: 

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
  #- jekyll-redirect-from

sass:
  # sass_dir: _sass
  style: compressed # possible values: nested expanded compact compressed

# assets:
#   sources:
#     - _assets

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

collections:
  - team_members
  - news

lang: 'en'
# Translation strings
t:
  four_0_four: '404'
  four_0_four_content: 'Page content not found'
  about: 'About'
  accept: 'Accept'
  accept_content: 'By using this site, you agree to our updated Privacy Policy.'
  advanced: 'Advanced'
  age_related_conditions: 'Age Related Conditions'
  age_related_content: 'Care Campus'' Age Realted Conditions focuses on the health challlenges that can occur as we age.  As a normal part of the ageing process, indepdence can be impaired as health is impacted.  Caregivers need to understand how they can provide assistance to support independence when health is increasingly compromised.'
  assisted_living: 'Assisted Living'
  basics: 'Basics'
  beginner: 'Beginner'
  care_safety: 'Care Safety'
  care_safety_content: 'Care Campus'' Care Safety takes the persoective of the person under care and how to provide them the best quality care to assure safetzy.  It also approaches safety from the perspetive of the person providing care, the care giver, to help them see the signals early and deal with situations that can compromise their safety.  There is also an emphasis on careing for the carer to prioritize and assure the health and well-being of the person providing care.  Disaster preparedness is also covered.'
  care_campus_is_for: 'Care Campus is for ...'
  care_campus_content: 'Care Campus helps famliy members learn how to care with confidence.  Care Campus'' certification program can help anyone seeking to become qualified as a paid care worker, one of the 21st century''s fastest growing vocations.  Care Campus partners with care providers to help train and accredit their staff. Care Campus also offers continuing education to help caregivers remain current with the latest advancements in caregiving.'
  coming_soon: 'Coming Soon'
  complex_care: 'Complex Care'
  complex_care_content: 'Care Campus'' Complex Care provides you with the knowledge, awareness, and insights needed to care for older adults with progressive physical or cognitive impairment, dementia and other complex situations.  We priotize the person under care and cover topics such as agresssion, agitation and anxiety, depression, hallucination, sleeplessnes and wandering and provide you the information you need to help older adults to age with dignity to enhance well-being and quality of life.'
  copyright_content: 'Bostel Technologies'
  care_with_confidence: 'Care with Confidence'
  caregiving_content: 'Caregiving is one of the fastest growing vocations in the world. We help you secure a future in it.'
  certification: 'Certification'
  certification_content: '<p>Care Campus'' accredited and certified curriculum allows you to learn as you go, with the ability to complete the course work in a way that fits with your schedule.</p><p>As a caregiver, you will gain the satisfaction that comes from knowing you have helped older adults to live their best life, despite their circumstances.</p><p>User success is measured through quizzes at the lesson level, tests at the module & course level, and exams at the program level, and by certificates of completion as well as optional, blockchain enabled certification.</p>'
  contact: 'Contact'
  contact_bostel: 'Contact Bostel'
  contact_us: 'Contact Us'
  contact_subtitle: 'Care with Confidence'
  contact_content: '<p>Care Campus provides training for family members, paid caregivers, and community health workers focused on supporting older adults to age with dignity. Please enter your information and we will notify you when we release new lessons, modules, courses, and programs, as well as when we host new events.</p>'
  courses: 'Courses'
  diagnosing_skin_cancer_melody: 'Diagnosing Skin Cancer with Melody'
  expert: 'Expert'
  families: 'Families'
  footer_copy: 'Bostel Technologies is a clinical-stage healthcare company that has developed Melody, a patented unique Dual Deep Learning technology in order to facilitate the diagnosis of skin cancer by dermoscopy.'
  fundamentals: 'Fundamentals'
  fundamentals_content: 'Care Campus'' Fundamentals provides you with knowledge, awareness, and insights into the key factors associated with effective caregiving for older adults.  Our goal is to empower you to support the health, independence, and well-being of your clients and loved ones through person-centered, high-quality care.  Upon successfully completing five courses courses in this Level I Certification Program, you will be eligible to proceed to specialized courses and pursue continuing education credit or further certification.'
  intermediate: 'Intermediate'
  get_started: 'Get Started'
  home_care: 'Home Care'
  login: 'Login'
  introduction: 'Introduction'
  intro_content: 'Care Campus'' Introduction provides an overview of the vocation of caregiving, how to best support activities for daily living, how to idendy and deal with age-related conditions and when to call a healthcare professional.  We cover connective technology and how it can play a role.  We empasize the need to care for yourself, when caring for others.  The person-center approach enables you to understand the needs and concerns of the person under care and how to prioritize them in your care plan.'
  jobs_content: '<p>The population aged 60 and above is the fastest growing demographic in the world.  With one billion projected for this age group by 2020, and two billion by 2025, the world needs to find a better way to care for them.</p><p>Caregiving is recognized as one of the fastest growing vocations in the world.  This rapidly expanding domain creates jobs with meaning that help older adults to thrive while having the potential to lower the overall costs of healthcare.</p><p>We took on the challenge of professionalizing the vocation of caregiving after seeing first hand the profound difference in well-being for people under skilled care.  Working with experts from around the world our goal is democratize the insights from universities, care providers, and other healthcare authorities by creating a ciricculum that is readily accessible through our online platform.</p>'
  jobs_with_meaning: 'Jobs with <span class="highlight">meaning</span> for the 21st century'
  kickstart_your_future: 'Kickstart Your Future'
  leading_experts: 'Leading Experts'
  learn_more: 'Learn More'
  long_term_care: 'Long Term Care'
  meaningful_work_has_future: '&ldquo;Meaningful work that <span class="highlight">has a future&rdquo;</span>'
  news: 'News'
  news_subtitle: 'Press releases, news stories, and articles'
  our_team: 'Our Team'
  our_caregiving_programs: 'Our Caregiving Programs'
  press_releases_news_articles: 'Press releases,<br />News stories and Articles'
  prevention_over_treatment: 'Prevention<br />Over Treatment'
  programs: 'Programs'
  publications: 'Publications'
  request_more_information: 'Request More Information'
  ready_to_get_started: 'Ready to get started?'
  references: 'References'
  references_subtitle: 'Further reading to better understand the issues and solutions around healthy aging'
  research_development: 'Research & Development'
  research_development_subtitle: 'Partner with us to shape the future'
  research_development_content: '<p>The commercial activities of Care Campus are supported by research and development conducted by Geneva-based non-profit Care Health & Technology Association.  Care Health & Technology Association conducts research and develops training programs, both on-line and in-person, products, tools and technology that advance care and care delivery for older adults to help them age with dignity through a more person-centered approach to care.</p>'
  scroll: 'Scroll'
  team: 'Team'
  thanks_for_your_interest: 'Thanks for your interest'
  terms_of_use: 'Terms of Use'
  terms_of_use_subtitle: 'Please Read These Terms of Use Carefully Before Using This Website'
  testimonials: 'Testimonials'
  testimonial: 'I wanted to find work that had a future, something that could turn into a career while helping people at the same time.  I am so happy I signed up with Care Campus and become certified.  Now I am helping people live their best life as they age while continuing to learn how to improve my skills and insights.  Thanks Care Campus!'
  testimonial_author: 'Tanzie Rahman'
  testimonial_title: 'Care Campus Graduate'
  upskill_for_better_future: 'Upskill For a Better Future'    